### PR TITLE
Use 1 instead of yes because it can be parsed

### LINKED ISSUE #203: Setting RTX_YES=yes breaks default configuration
Hi,

this action sets the `RTX_YES` variable to `yes`, but this value is not supported in the latest `rtx` version:
image

### PR DESCRIPTION
**Pull request by FalkWoldmann**
fixes #203

### CODE REVIEW

**Comment by rplankenhorn** [comment]
@FalkWoldmann Thanks for fixing this!  Running into this too.

@jdx Maybe we should fix the version of RTX within the action instead of always using the latest?  That way we can handle breaking changes a little more elegantly.

**Comment by rouge8** [comment]
@jdx can you make a release with this change? `jdx/rtx-action@v1` as recommended in the README is still failing

**Comment by jdx** [comment]
it's out

**Comment by kumichou** [comment]
@jdx Is there any reason why the `v1` tag isn't repointed to the SHA of `v1.2.6` that has the correction?

**Comment by jdx** [comment]
no reason other than me not knowing how to use git very well :)

**Comment by kumichou** [comment]
Lol oops! Well, thank you for repointing it. Corrected our busted builds.

**Pull request merged**
